// <auto-generated />
using System;
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(SzpContext))]
    partial class SzpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Historia_zmian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Historia_zmianId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("data_zmiany")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_uzytkownika")
                        .HasColumnType("int");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoriaZmian");
                });

            modelBuilder.Entity("CodeFirst.Models.Projekty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjektyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_startu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_zakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_kierownika_projektu")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("id_kierownika_projektu")
                        .IsUnique();

                    b.ToTable("Projekty");
                });

            modelBuilder.Entity("CodeFirst.Models.PrzeznaczenieWiadomosci", b =>
                {
                    b.Property<int>("Przeznaczenie_wiadomosciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Przeznaczenie_wiadomosciId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Przeznaczenie_wiadomosciId"));

                    b.Property<string>("Tresc_wiadomosci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_odbiorcy")
                        .HasColumnType("int");

                    b.HasKey("Przeznaczenie_wiadomosciId");

                    b.HasIndex("id_odbiorcy");

                    b.ToTable("PrzeznaczenieWiadomosci");
                });

            modelBuilder.Entity("CodeFirst.Models.Raporty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RaportyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("czas_pracy")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_uzytkownika")
                        .HasColumnType("int");

                    b.Property<decimal>("koszt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("id_uzytkownika");

                    b.ToTable("Raporty");
                });

            modelBuilder.Entity("CodeFirst.Models.Uzytkownicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UzytkownicyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_projektu")
                        .HasColumnType("int");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("id_projektu");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("CodeFirst.Models.Wiadomosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WiadomosciId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PrzeznaczenieWiadomosciPrzeznaczenie_wiadomosciId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_nadawcy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrzeznaczenieWiadomosciPrzeznaczenie_wiadomosciId");

                    b.HasIndex("id_nadawcy");

                    b.ToTable("Wiadomosci");
                });

            modelBuilder.Entity("CodeFirst.Models.Zadania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZadaniaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_startu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_zakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_projektu")
                        .HasColumnType("int");

                    b.Property<int>("id_uzytkownika")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("id_projektu");

                    b.HasIndex("id_uzytkownika");

                    b.ToTable("Zadania");
                });

            modelBuilder.Entity("CodeFirst.Models.Zasoby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZasobyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_projektu")
                        .HasColumnType("int");

                    b.Property<string>("typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("id_projektu");

                    b.ToTable("Zasoby");
                });

            modelBuilder.Entity("CodeFirst.Models.Zmiany_uzytkownika", b =>
                {
                    b.Property<int>("Id_uzytkownika")
                        .HasColumnType("int")
                        .HasColumnName("Zmiany_uzytkownikaId");

                    b.Property<DateTime>("data_zmiany")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_historia_zmian")
                        .HasColumnType("int");

                    b.HasKey("Id_uzytkownika");

                    b.HasIndex("id_historia_zmian");

                    b.ToTable("ZmianyUzytkownika");
                });

            modelBuilder.Entity("CodeFirst.Models.Projekty", b =>
                {
                    b.HasOne("CodeFirst.Models.Uzytkownicy", "KierownikProjektu")
                        .WithOne("Projekt")
                        .HasForeignKey("CodeFirst.Models.Projekty", "id_kierownika_projektu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Projekty_Uzytkownicy_id_kierownika_projektu");

                    b.Navigation("KierownikProjektu");
                });

            modelBuilder.Entity("CodeFirst.Models.PrzeznaczenieWiadomosci", b =>
                {
                    b.HasOne("CodeFirst.Models.Uzytkownicy", "Uzytkownicy")
                        .WithMany("PrzeznaczenieWiadomosciCollection")
                        .HasForeignKey("id_odbiorcy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("CodeFirst.Models.Raporty", b =>
                {
                    b.HasOne("CodeFirst.Models.Uzytkownicy", "Uzytkownicy")
                        .WithMany("RaportyCollection")
                        .HasForeignKey("id_uzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("CodeFirst.Models.Uzytkownicy", b =>
                {
                    b.HasOne("CodeFirst.Models.Projekty", "ProjektyCollection")
                        .WithMany("UzytkownicyCollection")
                        .HasForeignKey("id_projektu");

                    b.Navigation("ProjektyCollection");
                });

            modelBuilder.Entity("CodeFirst.Models.Wiadomosci", b =>
                {
                    b.HasOne("CodeFirst.Models.PrzeznaczenieWiadomosci", null)
                        .WithMany("Wiadomosci")
                        .HasForeignKey("PrzeznaczenieWiadomosciPrzeznaczenie_wiadomosciId");

                    b.HasOne("CodeFirst.Models.Uzytkownicy", "Nadawca")
                        .WithMany("WiadomosciCollection")
                        .HasForeignKey("id_nadawcy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Nadawca");
                });

            modelBuilder.Entity("CodeFirst.Models.Zadania", b =>
                {
                    b.HasOne("CodeFirst.Models.Projekty", "Projekty")
                        .WithMany("ZadaniaCollection")
                        .HasForeignKey("id_projektu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Uzytkownicy", "Uzytkownicy")
                        .WithMany("ZadaniaCollection")
                        .HasForeignKey("id_uzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekty");

                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("CodeFirst.Models.Zasoby", b =>
                {
                    b.HasOne("CodeFirst.Models.Projekty", "Projekty")
                        .WithMany("ZasobyCollection")
                        .HasForeignKey("id_projektu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("CodeFirst.Models.Zmiany_uzytkownika", b =>
                {
                    b.HasOne("CodeFirst.Models.Uzytkownicy", "Uzytkownicy")
                        .WithMany("ZmianyUzytkownikaCollection")
                        .HasForeignKey("Id_uzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Historia_zmian", "Historia_zmian")
                        .WithMany("ZmianyUzytkownikaCollection")
                        .HasForeignKey("id_historia_zmian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historia_zmian");

                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("CodeFirst.Models.Historia_zmian", b =>
                {
                    b.Navigation("ZmianyUzytkownikaCollection");
                });

            modelBuilder.Entity("CodeFirst.Models.Projekty", b =>
                {
                    b.Navigation("UzytkownicyCollection");

                    b.Navigation("ZadaniaCollection");

                    b.Navigation("ZasobyCollection");
                });

            modelBuilder.Entity("CodeFirst.Models.PrzeznaczenieWiadomosci", b =>
                {
                    b.Navigation("Wiadomosci");
                });

            modelBuilder.Entity("CodeFirst.Models.Uzytkownicy", b =>
                {
                    b.Navigation("Projekt")
                        .IsRequired();

                    b.Navigation("PrzeznaczenieWiadomosciCollection");

                    b.Navigation("RaportyCollection");

                    b.Navigation("WiadomosciCollection");

                    b.Navigation("ZadaniaCollection");

                    b.Navigation("ZmianyUzytkownikaCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
